parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  tsconfigRootDir: '.'
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - 'import'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
root: true
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  'import/no-unresolved': 'error'
  'import/extensions':
    - error
    - ignorePackages
    -
      js: never
      ts: never
  'import/named': error
  'import/namespace': error

settings:
  import/parser:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    node:
      project: tsconfig.json
    typescript:
      alwaysTryTypes: true
      project: './tsconfig.json'
